apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-app
  labels:
    app: aceest
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: aceest
  template:
    metadata:
      labels:
        app: aceest
    spec:
      containers:
        - name: aceest-app
          image: your-dockerhub-user/aceest-fitness:latest
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
